# Generated by Django 2.2.3 on 2019-07-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_githubrepository_product_productslug_project_projectslug")
    ]

    operations = [
        migrations.AlterModelOptions(name="product", options={"ordering": ("name",)}),
        migrations.AlterModelOptions(
            name="project", options={"ordering": ("-created_at", "name")}
        ),
    ]
