# Generated by Django 2.2.2 on 2019-06-26 06:06

import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models

ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"


class Migration(migrations.Migration):

    dependencies = [("api", "0002_product")]

    operations = [
        migrations.CreateModel(
            name="ProductDependency",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet=ALPHABET,
                        min_length=7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="api.Product",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
