# Generated by Django 2.2.3 on 2019-07-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_githubrepository_product_productslug_project_projectslug")
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="name", field=models.CharField(max_length=50)
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("branch_name", "product"), ("name", "product")},
        ),
    ]
