# Generated by Django 2.2.3 on 2019-08-02 22:15

import django.db.models.deletion
import hashid_field.field
from django.conf import settings
from django.db import migrations, models

import sfdo_template_helpers.fields.markdown
import sfdo_template_helpers.slugs

ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"


class Migration(migrations.Migration):

    dependencies = [("api", "0003_project_projectslug")]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet=ALPHABET,
                        min_length=7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    sfdo_template_helpers.fields.markdown.MarkdownField(
                        blank=True, property_suffix="_markdown"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="api.Project",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "name"),
                "unique_together": {("name", "project")},
            },
            bases=(sfdo_template_helpers.slugs.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TaskSlug",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "If multiple slugs are active, we will default to the most "
                            "recent."
                        ),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slugs",
                        to="api.Task",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",), "abstract": False},
        ),
    ]
