# Generated by Django 2.2.3 on 2019-07-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_task"),
        ("api", "0003_change_project_name_uniqueness"),
    ]

    operations = []
