# Generated by Django 2.2.2 on 2019-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0003_project_projectslug")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="pr_url",
            field=models.URLField(null=True, unique=True),
        )
    ]
