# Generated by Django 2.2.4 on 2019-08-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0004_task_taskslug")]

    operations = [
        migrations.RenameModel(old_name="Product", new_name="Repository"),
        migrations.RenameModel(old_name="ProductSlug", new_name="RepositorySlug"),
    ]
