# Generated by Django 2.2.4 on 2019-08-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0005_rename_product_to_repository")]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="product", new_name="repository"
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "repository"), ("branch_name", "repository")},
        ),
    ]
