# Generated by Django 2.2.4 on 2019-08-16 17:38

import django.db.models.deletion
import hashid_field.field
from django.conf import settings
from django.db import migrations, models

import sfdo_template_helpers.fields.string

ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"


class Migration(migrations.Migration):

    dependencies = [("api", "0007_repository_verbose_name_plural")]

    operations = [
        migrations.CreateModel(
            name="ScratchOrg",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet=ALPHABET,
                        min_length=7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "org_type",
                    sfdo_template_helpers.fields.string.StringField(
                        choices=[("Dev", "Dev"), ("QA", "QA")]
                    ),
                ),
                ("last_modified_at", models.DateTimeField(null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "latest_commit",
                    sfdo_template_helpers.fields.string.StringField(blank=True),
                ),
                ("latest_commit_url", models.URLField(blank=True)),
                ("url", models.URLField()),
                ("has_changes", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.Task"
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
