# Generated by Django 2.2.5 on 2019-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0012_update_project_unique_together")]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="latest_commit_at",
            field=models.DateTimeField(null=True),
        )
    ]
