# Generated by Django 2.2.4 on 2019-09-05 16:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0012_update_project_unique_together")]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="config",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        )
    ]
