# Generated by Django 2.2.4 on 2019-09-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_scratchorg_config'),
        ('api', '0013_scratchorg_latest_commit_at'),
    ]

    operations = [
    ]
