# Generated by Django 2.2.5 on 2019-09-09 15:53

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0014_merge_20190905_2214")]

    operations = [
        migrations.AlterField(
            model_name="scratchorg",
            name="config",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        )
    ]
