# Generated by Django 2.2.5 on 2019-09-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0015_scratchorg_config_encoder")]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="currently_refreshing_changes",
            field=models.BooleanField(default=False),
        )
    ]
