# Generated by Django 2.2.5 on 2019-09-16 19:37

from os import environ

from django.db import migrations


def forwards(apps, schema_editor):
    SocialApp = apps.get_model("socialaccount", "SocialApp")

    client_id = environ.get("SF_CLIENT_ID")
    secret = environ.get("SF_CLIENT_SECRET")
    if client_id and secret:
        SocialApp.objects.get_or_create(
            provider=f"salesforce-production",
            defaults=dict(
                name=f"Salesforce Production",
                key="https://login.salesforce.com/",
                client_id=client_id,
                secret=secret,
            ),
        )


def backwards(apps, schema_editor):
    SocialApp = apps.get_model("socialaccount", "SocialApp")
    SocialApp.objects.filter(provider="salesforce-production").delete()


class Migration(migrations.Migration):

    dependencies = [("api", "0015_scratchorg_config_encoder")]

    operations = [migrations.RunPython(forwards, backwards)]
