# Generated by Django 2.2.6 on 2019-10-07 20:25

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0018_allow_blank_fields")]

    operations = [
        migrations.AlterField(
            model_name="scratchorg",
            name="config",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        )
    ]
