# Generated by Django 2.2.5 on 2019-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0018_allow_blank_fields")]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="login_url",
            field=models.URLField(null=True, blank=True),
        )
    ]
