# Generated by Django 2.2.6 on 2019-10-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0018_allow_blank_fields")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="branch_name",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="branch_name",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
