# Generated by Django 2.2.5 on 2019-09-23 22:17

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0019_scratchorg_login_url")]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="latest_revision_numbers",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        )
    ]
