# Generated by Django 2.2.5 on 2019-10-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0021_has_changes_to_unsaved_changes")]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="currently_capturing_changes",
            field=models.BooleanField(default=False),
        )
    ]
