# Generated by Django 2.2.6 on 2019-10-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_lengthen_branch_names"),
        ("api", "0022_scratchorg_currently_capturing_changes"),
    ]

    operations = []
