# Generated by Django 2.2.6 on 2019-10-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_merge_20191007_2134"),
        ("api", "0023_merge_20191007_2132"),
    ]

    operations = []
