# Generated by Django 2.2.6 on 2019-10-09 21:26

import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0025_allow_blank_json_fields")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=sfdo_template_helpers.fields.string.StringField(),
        ),
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=sfdo_template_helpers.fields.string.StringField(unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=sfdo_template_helpers.fields.string.StringField(),
        ),
    ]
