# Generated by Django 2.2.6 on 2019-10-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0026_use_stringfield_everywhere")]

    operations = [
        migrations.AddField(
            model_name="githubrepository",
            name="repo_id",
            field=models.IntegerField(null=True),
        )
    ]
