# Generated by Django 2.2.6 on 2019-10-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0027_githubrepository_repo_id")]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="repo_id",
            field=models.IntegerField(null=True, blank=True, unique=True),
        )
    ]
