# Generated by Django 2.2.6 on 2019-10-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_add_socialapps"),
        ("api", "0027_remove_scratchorg_login_url"),
    ]

    operations = []
