# Generated by Django 2.2.6 on 2019-10-14 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0028_repository_repo_id")]

    operations = [
        migrations.RenameField(
            model_name="githubrepository", old_name="url", new_name="repo_url"
        )
    ]
