# Generated by Django 2.2.6 on 2019-10-15 18:41

from urllib.parse import urlparse

from django.db import migrations, models

import sfdo_template_helpers.fields.string

from ..gh import get_repo_info


def extract_owner_and_name(gh_url):
    path = urlparse(gh_url).path
    _, owner, name, *_ = path.split("/")
    return owner, name


def set_repo_owner_and_name(apps, schema_editor):
    Repository = apps.get_model("api", "Repository")
    for instance in Repository.objects.all():
        owner, name = extract_owner_and_name(instance.repo_url)
        if not instance.repo_name:
            instance.repo_name = name
        if not instance.repo_owner:
            instance.repo_owner = owner
        instance.save()


def set_repo_url(apps, schema_editor):
    Repository = apps.get_model("api", "Repository")
    for instance in Repository.objects.all():
        owner = instance.repo_owner
        name = instance.repo_name
        instance.repo_url = f"https://github.com/{owner}/{name}"
        instance.save()


def set_repo_id(apps, schema_editor):
    GitHubRepository = apps.get_model("api", "GitHubRepository")
    for instance in GitHubRepository.objects.all():
        if not instance.repo_id:
            owner, name = extract_owner_and_name(instance.repo_url)
            repo = get_repo_info(instance.user, repo_owner=owner, repo_name=name)
            instance.repo_id = repo.id
            instance.save()


class Migration(migrations.Migration):
    dependencies = [("api", "0029_rename_github_url_field")]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="repo_name",
            field=sfdo_template_helpers.fields.string.StringField(null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="repo_owner",
            field=sfdo_template_helpers.fields.string.StringField(null=True),
        ),
        migrations.RunPython(set_repo_owner_and_name, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="repository",
            name="repo_name",
            field=sfdo_template_helpers.fields.string.StringField(),
        ),
        migrations.AlterField(
            model_name="repository",
            name="repo_owner",
            field=sfdo_template_helpers.fields.string.StringField(),
        ),
        migrations.AlterUniqueTogether(
            name="repository", unique_together={("repo_owner", "repo_name")}
        ),
        migrations.AlterField(
            model_name="repository",
            name="repo_url",
            field=models.URLField(unique=True, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, set_repo_url),
        migrations.RemoveField(model_name="repository", name="repo_url"),
        migrations.AlterField(
            model_name="githubrepository",
            name="repo_id",
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(set_repo_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="githubrepository",
            name="repo_id",
            field=models.IntegerField(unique=True),
        ),
    ]
