# Generated by Django 2.2.6 on 2019-10-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_rename_github_url_field"),
        ("api", "0027_remove_scratchorg_login_url"),
    ]

    operations = []
