# Generated by Django 2.2.6 on 2019-10-23 18:38

import sfdo_template_helpers.fields.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0030_merge_20191023_1833")]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="repo_name",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="repo_owner",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="githubrepository",
            name="repo_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="repository", unique_together={("repo_owner", "repo_name")}
        ),
        migrations.RemoveField(model_name="repository", name="repo_url"),
    ]
