# Generated by Django 2.2.6 on 2019-10-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_replace_repo_url_with_repo_id"),
        ("api", "0027_remove_scratchorg_login_url"),
    ]

    operations = []
