# Generated by Django 2.2.6 on 2019-10-23 18:38

from urllib.parse import urlparse

import sfdo_template_helpers.fields.string
from django.db import migrations, models


def extract_owner_and_name(gh_url):
    path = urlparse(gh_url).path
    _, owner, name, *_ = path.split("/")
    return owner, name


def set_repo_owner_and_name(apps, schema_editor):
    Repository = apps.get_model("api", "Repository")
    for instance in Repository.objects.all():
        owner, name = extract_owner_and_name(instance.repo_url)
        if not instance.repo_name:
            instance.repo_name = name
        if not instance.repo_owner:
            instance.repo_owner = owner
        instance.save()


def set_repo_url(apps, schema_editor):
    Repository = apps.get_model("api", "Repository")
    for instance in Repository.objects.all():
        owner = instance.repo_owner
        name = instance.repo_name
        instance.repo_url = f"https://github.com/{owner}/{name}"
        instance.save()


class Migration(migrations.Migration):

    dependencies = [("api", "0030_merge_20191023_1833")]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="repo_name",
            field=sfdo_template_helpers.fields.string.StringField(null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="repo_owner",
            field=sfdo_template_helpers.fields.string.StringField(null=True),
        ),
        migrations.RunPython(set_repo_owner_and_name, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="repository",
            name="repo_name",
            field=sfdo_template_helpers.fields.string.StringField(),
        ),
        migrations.AlterField(
            model_name="repository",
            name="repo_owner",
            field=sfdo_template_helpers.fields.string.StringField(),
        ),
        migrations.AlterUniqueTogether(
            name="repository", unique_together={("repo_owner", "repo_name")}
        ),
        migrations.AlterField(
            model_name="repository",
            name="repo_url",
            field=models.URLField(unique=True, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, set_repo_url),
        migrations.RemoveField(model_name="repository", name="repo_url"),
    ]
