# Generated by Django 2.2.6 on 2019-10-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_merge_20191023_2024"),
        ("api", "0031_auto_20191023_1838"),
    ]

    operations = []
