# Generated by Django 2.2.6 on 2019-11-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0033_scratchorg_owner_sf_id")]

    operations = [
        migrations.AlterField(
            model_name="githubrepository", name="repo_id", field=models.IntegerField()
        ),
        migrations.AlterUniqueTogether(
            name="githubrepository", unique_together={("user", "repo_id")}
        ),
    ]
