# Generated by Django 2.2.6 on 2019-11-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0034_githubrepository_unique")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currently_fetching_repos",
            field=models.BooleanField(default=False),
        )
    ]
