# Generated by Django 2.2.6 on 2019-11-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0034_githubrepository_unique")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="has_unmerged_commits",
            field=models.BooleanField(default=False),
        )
    ]
