# Generated by Django 2.2.7 on 2019-11-13 17:22

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0034_githubrepository_unique")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="branch_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w/]+\\Z"),
                        (
                            "Enter a valid 'branch' consisting of Unicode letters, "
                            "numbers, underscores, slashes, or hyphens."
                        ),
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="branch_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w/]+\\Z"),
                        (
                            "Enter a valid 'branch' consisting of Unicode letters, "
                            "numbers, underscores, slashes, or hyphens."
                        ),
                        "invalid",
                    )
                ],
            ),
        ),
    ]
