# Generated by Django 2.2.6 on 2019-11-12 18:28

from django.db import migrations

import metashare.api.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0034_githubrepository_unique")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="branch_name",
            field=metashare.api.fields.BranchField(
                blank=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="branch_name",
            field=metashare.api.fields.BranchField(
                blank=True, max_length=100, null=True
            ),
        ),
    ]
