# Generated by Django 2.2.7 on 2019-11-18 19:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_merge_20191113_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="commits",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="commits",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
