# Generated by Django 2.2.6 on 2019-11-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0036_task_currently_creating_pr")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="pr_number",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
