# Generated by Django 2.2.7 on 2019-11-19 18:53

import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_auto_20191118_1931"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="hook_secret",
            field=sfdo_template_helpers.fields.string.StringField(
                editable=False, null=True
            ),
        ),
    ]
