# Generated by Django 2.2.7 on 2019-11-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_merge_20191113_1846"),
        ("api", "0036_merge_20191113_1851"),
    ]

    operations = []
