# Generated by Django 2.2.8 on 2019-12-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_project_task_commits"),
        ("api", "0039_merge_20191113_2006"),
    ]

    operations = []
