# Generated by Django 2.2.7 on 2019-11-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_repository_hook_secret"),
        ("api", "0039_merge_20191113_2006"),
    ]

    operations = []
