# Generated by Django 2.2.8 on 2019-12-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0039_merge_20191113_2006")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="currently_creating_pr",
            field=models.BooleanField(default=False),
        )
    ]
