# Generated by Django 2.2.8 on 2019-12-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_merge_20191122_1720"),
        ("api", "0040_task_status"),
    ]

    operations = []
