# Generated by Django 2.2.8 on 2019-12-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_task_status"),
        ("api", "0040_task_commits_origin_sha"),
    ]

    operations = []
