# Generated by Django 2.2.8 on 2019-12-13 18:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_auto_20191211_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ms_commits",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
