# Generated by Django 2.2.8 on 2019-12-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_project_pr_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="has_unmerged_commits",
            field=models.BooleanField(default=False),
        ),
    ]
