# Generated by Django 2.2.8 on 2019-12-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_project_has_unmerged_commits"),
        ("api", "0041_merge_20191205_2230"),
    ]

    operations = []
