# Generated by Django 2.2.8 on 2019-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_merge_20191219_2351"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pr_is_open",
            field=models.BooleanField(default=False),
        ),
    ]
