# Generated by Django 2.2.8 on 2019-12-10 21:42

import re

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0043_merge_20191209_2335")]

    operations = [
        migrations.RemoveField(model_name="repository", name="hook_secret"),
        migrations.AddField(
            model_name="repository",
            name="branch_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w/]+\\Z"),
                        (
                            "Enter a valid 'branch' consisting of Unicode letters, "
                            "numbers, underscores, slashes, or hyphens."
                        ),
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="commits",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
