# Generated by Django 2.2.9 on 2019-12-23 19:26

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_repository_branch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="branch_name",
            field=models.CharField(
                blank=True,
                default="master",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w/]+\\Z"),
                        (
                            "Enter a valid 'branch' consisting of Unicode letters, "
                            "numbers, underscores, slashes, or hyphens."
                        ),
                        "invalid",
                    )
                ],
            ),
        ),
    ]
