# Generated by Django 2.2.9 on 2019-12-27 19:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_repository_branch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="github_users",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list
            ),
        ),
    ]
