# Generated by Django 3.0.2 on 2020-01-06 21:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_repo_project_github_users"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="assignee",),
        migrations.AddField(
            model_name="task",
            name="assigned_dev",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_qa",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
