# Generated by Django 3.0.2 on 2020-01-06 21:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20200106_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='github_users',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
