# Generated by Django 2.2.9 on 2019-12-31 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_repository_github_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="assigned_users",
            field=models.ManyToManyField(
                related_name="assigned_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
