# Generated by Django 3.0.2 on 2020-01-22 18:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_task_github_users"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="assignee",),
        migrations.RemoveField(model_name="task", name="github_users",),
        migrations.AddField(
            model_name="task",
            name="assigned_dev",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_qa",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
    ]
