# Generated by Django 3.0.2 on 2020-01-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_merge_20200123_2142"),
        ("api", "0049_rename_scratchorg_owner_sf_id"),
    ]

    operations = []
