# Generated by Django 3.0.3 on 2020-02-10 17:52

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_merge_20200130_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="valid_target_directories",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
