# Generated by Django 3.0.2 on 2020-02-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_merge_20200130_2145"),
        ("api", "0047_add_task_review"),
    ]

    operations = []
