# Generated by Django 3.0.3 on 2020-02-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_merge_20200201_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scratchorg',
            old_name='has_ever_been_visited',
            new_name='has_been_visited',
        ),
    ]
