# Generated by Django 3.0.3 on 2020-02-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_scratchorg_valid_target_directories"),
        ("api", "0052_scratchorg_expiry_job_id"),
    ]

    operations = []
