# Generated by Django 3.0.3 on 2020-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_task_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="currently_submitting_review",
            field=models.BooleanField(default=False),
        ),
    ]
