# Generated by Django 3.0.3 on 2020-02-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_task_currently_submitting_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="review_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
