# Generated by Django 3.0.3 on 2020-02-17 19:17

import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_task_review_submitted_at_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="review_sha",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, null=True
            ),
        ),
    ]
