# Generated by Django 3.0.3 on 2020-03-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_task_review_sha"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="last_checked_unsaved_changes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
