# Generated by Django 3.0.3 on 2020-03-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_task_review_sha"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="use_global_devhub",
            field=models.BooleanField(default=False),
        ),
    ]
