# Generated by Django 3.0.3 on 2020-02-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_task_review_sha"),
        ("api", "0053_merge_20200217_1951"),
    ]

    operations = []
