# Generated by Django 3.0.4 on 2020-03-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_merge_20200220_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pr_is_merged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planned", "Planned"),
                    ("In Progress", "In Progress"),
                    ("Review", "Review"),
                    ("Merged", "Merged"),
                ],
                default="Planned",
                max_length=20,
            ),
        ),
    ]
