# Generated by Django 3.0.3 on 2020-02-20 19:39

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_merge_20200220_1748"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scratchorg",
            name="valid_target_directories",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
