# Generated by Django 3.0.3 on 2020-03-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_scratchorg_last_checked_unsaved_changes_at'),
        ('api', '0058_merge_20200220_1748'),
    ]

    operations = [
    ]
