# Generated by Django 3.0.3 on 2020-03-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_merge_20200220_1748"),
        ("api", "0059_auto_20200304_0535"),
    ]

    operations = []
