# Generated by Django 3.0.4 on 2020-03-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_merge_20200305_2105"),
        ("api", "0061_fix_project_status"),
    ]

    operations = []
