# Generated by Django 3.0.4 on 2020-03-23 16:12

from django.db import migrations


def forwards(apps, schema_editor):
    SocialApp = apps.get_model("socialaccount", "SocialApp")
    SocialAccount = apps.get_model("socialaccount", "SocialAccount")
    SocialToken = apps.get_model("socialaccount", "SocialToken")

    # update salesforce
    try:
        app = SocialApp.objects.get(provider="salesforce-production")
    except SocialApp.DoesNotExist:
        pass
    else:
        app.provider = "salesforce"
        app.client_id = "-"
        app.secret = ""
        app.save()

        SocialAccount.objects.filter(provider="salesforce-production").update(
            provider="salesforce"
        )
        SocialAccount.objects.filter(provider="salesforce-custom").update(
            provider="salesforce"
        )
        SocialToken.objects.filter().update()

        custom_app = SocialApp.objects.get(provider="salesforce-custom")
        SocialToken.objects.filter(app=custom_app).update(app=app)
        custom_app.delete()

    # update github
    try:
        app = SocialApp.objects.get(provider="github", name="GitHub")
    except SocialApp.DoesNotExist:
        app = SocialApp(provider="github", name="GitHub")
    app.client_id = "-"
    app.secret = ""
    app.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_merge_20200318_1449"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
