#!/bin/sh

function dcr {
  docker-compose run --no-deps $@
}

STAGED_FILES=$(git diff --name-only --cached --diff-filter=d)

JS=()
SCSS=()
PY=()
PYI=()
OTHER=()

for FILENAME in $STAGED_FILES
do
    EXTENSION="${FILENAME##*.}"

    case $EXTENSION in
        js|ts|vue)
            JS+=($FILENAME)
            ;;
        scss)
            SCSS+=($FILENAME)
            ;;
        py)
            if [[ "$FILENAME" =~ mypy-stubs/.*\.py$ ]]; then
                printf "Do not commit .py files in mypy-stubs, only .pyi: ${FILENAME}\n"
                exit 1
            fi
            PY+=($FILENAME)
            ;;
        pyi)
            PYI+=($FILENAME)
            ;;
        *)
            OTHER+=($FILENAME)
            ;;
    esac
done

if [ ${#JS[@]} -ne 0 ]; then
    dcr client yarn lint:js ${JS[@]}
    git add ${JS[@]}
fi

if [ ${#SCSS[@]} -ne 0 ]; then
    dcr client prettier --write ${SCSS[@]}
    dcr client stylelint ${SCSS[@]}
    git add ${SCSS[@]}
fi

if [ ${#PY[@]} -ne 0 ]; then
    dcr web isort ${PY[@]}
    dcr web black ${PY[@]}
    dcr web flake8 ${PY[@]}
    dcr web mypy books
    git add ${PY[@]}
fi

if [ ${#PYI[@]} -ne 0 ]; then
    dcr web isort ${PYI[@]}
    dcr web black ${PYI[@]}
    dcr web mypy books
    git add ${PYI[@]}
fi

if [ ${#OTHER[@]} -ne 0 ]; then
    git add ${OTHER[@]}
fi
