# Generated by Django 2.2.4 on 2019-08-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0006_rename_product_foreignkey")]

    operations = [
        migrations.AlterModelOptions(
            name="repository",
            options={"ordering": ("name",), "verbose_name_plural": "repositories"},
        )
    ]
