# Generated by Django 2.2.4 on 2019-08-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0008_scratchorg")]

    operations = [
        migrations.AlterField(
            model_name="scratchorg",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="scratchorg", name="url", field=models.URLField(null=True)
        ),
    ]
