# Generated by Django 2.2.4 on 2019-08-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0009_add_nullables_to_scratch_org")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="branch_name",
            field=models.SlugField(default="task-branch"),
            preserve_default=False,
        )
    ]
