# Generated by Django 2.2.5 on 2019-09-17 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0017_scratchorg_delete_queued_at")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="branch_name",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="delete_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="last_modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="latest_commit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="branch_name",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
