# Generated by Django 2.2.6 on 2019-10-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_allow_blank_json_fields"),
        ("api", "0019_lengthen_branch_names"),
    ]

    operations = []
