# Generated by Django 2.2.5 on 2019-09-27 16:59

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0020_scratchorg_latest_revision_numbers")]

    operations = [
        migrations.RemoveField(model_name="scratchorg", name="has_changes"),
        migrations.AddField(
            model_name="scratchorg",
            name="unsaved_changes",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
