# Generated by Django 2.2.6 on 2019-10-08 19:15

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0024_merge_20191008_1914")]

    operations = [
        migrations.AlterField(
            model_name="scratchorg",
            name="latest_revision_numbers",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="unsaved_changes",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
