# Generated by Django 2.2.7 on 2019-11-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_user_currently_fetching_repos"),
        ("api", "0035_alter_project_task_branch_name"),
    ]

    operations = []
