# Generated by Django 2.2.8 on 2019-12-13 21:39

import django.contrib.postgres.fields.jsonb
import django.core.validators
import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_merge_20191113_2006"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="commits",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=list, blank=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="ms_commits",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=list, blank=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="origin_sha",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, null=True
            ),
        ),
    ]
