# Generated by Django 2.2.8 on 2019-12-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_task_pr_is_open"),
        ("api", "0042_project_has_unmerged_commits"),
    ]

    operations = []
