# Generated by Django 3.0.2 on 2020-01-07 22:08

import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_repository_branch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="devhub_username",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, null=True
            ),
        ),
    ]
