# Generated by Django 3.0.2 on 2020-01-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_repo_project_github_users"),
        ("api", "0046_user_devhub_username"),
    ]

    operations = []
