# Generated by Django 3.0.2 on 2020-01-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_repo_project_github_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="has_ever_been_visited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="review_submitted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="review_valid",
            field=models.BooleanField(default=False),
        ),
    ]
