# Generated by Django 3.0.2 on 2020-01-28 20:11

import sfdo_template_helpers.fields.string
from django.db import migrations


def set_org_owner_gh_username(apps, schema_editor):
    ScratchOrg = apps.get_model("api", "ScratchOrg")
    for instance in ScratchOrg.objects.filter(owner_gh_username=""):
        instance.owner_gh_username = instance.owner.username
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_task_assigned_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="owner_gh_username",
            field=sfdo_template_helpers.fields.string.StringField(blank=True),
        ),
        migrations.RunPython(set_org_owner_gh_username, migrations.RunPython.noop),
    ]
