# Generated by Django 3.0.2 on 2020-01-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_scratchorg_owner_gh_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scratchorg",
            old_name="owner_sf_id",
            new_name="owner_sf_username",
        ),
    ]
