# Generated by Django 3.0.3 on 2020-02-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_merge_20200130_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="currently_refreshing_org",
            field=models.BooleanField(default=False),
        ),
    ]
