# Generated by Django 3.0.3 on 2020-02-06 19:57

import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_scratchorg_currently_refreshing_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="expiry_job_id",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, null=True
            ),
        ),
    ]
