# Generated by Django 3.0.3 on 2020-02-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_rename_scratchorg_has_been_visited"),
        ("api", "0052_scratchorg_expiry_job_id"),
    ]

    operations = []
