# Generated by Django 3.0.3 on 2020-02-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_merge_20200211_1811"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Approved", "Approved"),
                    ("Changes requested", "Changes Requested"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
