# Generated by Django 3.0.3 on 2020-03-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_user_use_global_devhub"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="use_global_devhub",
            new_name="allow_devhub_override",
        ),
    ]
