# Generated by Django 3.0.4 on 2020-03-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_merge_20200305_2044"),
        ("api", "0059_track_project_status"),
    ]

    operations = []
