# Generated by Django 3.0.4 on 2020-03-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_update_socialapps"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="task", name="deleted_at", field=models.DateTimeField(null=True),
        ),
    ]
