# Generated by Django 3.0.4 on 2020-03-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_update_socialapps"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agreed_to_tos_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
