# Generated by Django 3.0.4 on 2020-03-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_user_agreed_to_tos_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="is_created",
            field=models.BooleanField(default=False),
        ),
    ]
