# Generated by Django 3.0.4 on 2020-03-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_user_agreed_to_tos_at"),
        ("api", "0064_add_soft_delete_to_projects_and_tasks"),
    ]

    operations = []
