# Generated by Django 3.0.4 on 2020-04-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_scratchorg_is_created"),
        ("api", "0065_siteprofile_siteprofiletranslation"),
    ]

    operations = []
