# Generated by Django 3.0.4 on 2020-04-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_merge_20200401_0038"),
        ("api", "0065_merge_20200330_2148"),
    ]

    operations = []
