# Generated by Django 3.0.4 on 2020-04-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_merge_20200401_1639"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg", name="cci_log", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scratchorg",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
