# Generated by Django 3.0.5 on 2020-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_merge_20200401_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
