# Generated by Django 3.0.5 on 2020-04-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_deleted_at_blank"),
        ("api", "0068_scratchorg_deleted_at"),
    ]

    operations = []
