# Generated by Django 3.0.5 on 2020-04-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_merge_20200408_2110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scratchorg",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
