# Generated by Django 3.0.5 on 2020-04-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_cascade_slug_deletion"),
        ("api", "0070_scratchorg_deleted_at_blank"),
    ]

    operations = []
