# Generated by Django 3.0.5 on 2020-05-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_merge_20200408_2121"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubrepository",
            name="repo_image_url",
            field=models.URLField(blank=True),
        ),
    ]
