# Generated by Django 3.0.5 on 2020-04-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_scratchorg_ignored_changes"),
        ("api", "0071_merge_20200408_2121"),
    ]

    operations = []
