# Generated by Django 3.0.6 on 2020-05-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_githubrepository_repo_image_url"),
        ("api", "0072_merge_20200423_1445"),
    ]

    operations = []
