# Generated by Django 3.0.5 on 2020-05-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_remove_name_project_constraint_on_tasks"),
        ("api", "0073_merge_20200520_1931"),
    ]

    operations = []
