# Generated by Django 3.0.6 on 2020-05-26 16:59

import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_remove_name_project_constraint_on_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="branch_prefix",
            field=sfdo_template_helpers.fields.string.StringField(blank=True),
        ),
    ]
