# Generated by Django 3.0.6 on 2020-05-28 14:40

import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_remove_name_project_constraint_on_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scratchorg",
            name="org_type",
            field=sfdo_template_helpers.fields.string.StringField(
                choices=[
                    ("Dev", "Dev"),
                    ("QA", "QA"),
                    ("Beta", "Beta"),
                    ("Release", "Release"),
                ]
            ),
        ),
    ]
