# Generated by Django 3.0.6 on 2020-05-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_add_more_scratchorg_types"),
        ("api", "0075_repository_branch_prefix"),
    ]

    operations = []
