# Generated by Django 3.0.6 on 2020-05-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_merge_20200521_1954"),
    ]

    operations = [
        migrations.RemoveField(model_name="githubrepository", name="repo_image_url",),
        migrations.AddField(
            model_name="repository",
            name="repo_image_url",
            field=models.URLField(blank=True),
        ),
    ]
