# Generated by Django 3.0.6 on 2020-05-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_repository_branch_prefix"),
        ("api", "0076_move_repo_image_url_to_repository"),
    ]

    operations = []
