# Generated by Django 3.0.6 on 2020-06-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_project_available_task_org_config_names"),
        ("api", "0078_repository_include_repo_image_url"),
    ]

    operations = []
