# Generated by Django 3.0.7 on 2020-06-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_project_currently_fetching_org_config_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="currently_reassigning_user",
            field=models.BooleanField(default=False),
        ),
    ]
