# Generated by Django 3.0.7 on 2020-06-08 19:30

import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("api", "0080_project_currently_fetching_org_config_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="devhub_username",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, default=""
            ),
        ),
    ]
