# Generated by Django 3.0.7 on 2020-06-08 19:51

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("api", "0081_no_nullable_devhub_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="branch_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w/]+\\Z"),
                        (
                            "Enter a valid 'branch' consisting of Unicode letters, "
                            "numbers, underscores, slashes, or hyphens."
                        ),
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="branch_name",
            field=models.CharField(
                blank=True,
                default="master",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w/]+\\Z"),
                        (
                            "Enter a valid 'branch' consisting of Unicode letters, "
                            "numbers, underscores, slashes, or hyphens."
                        ),
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="branch_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w/]+\\Z"),
                        (
                            "Enter a valid 'branch' consisting of Unicode letters, "
                            "numbers, underscores, slashes, or hyphens."
                        ),
                        "invalid",
                    )
                ],
            ),
        ),
    ]
