# Generated by Django 3.0.7 on 2020-06-08 21:36

import sfdo_template_helpers.fields.string
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("api", "0082_remove_more_nullable_strings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scratchorg",
            name="expiry_job_id",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="origin_sha",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="review_sha",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Approved", "Approved"),
                    ("Changes requested", "Changes Requested"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
