# Generated by Django 3.0.7 on 2020-06-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0083_remove_all_null_strings"),
        ("api", "0081_scratchorg_currently_reassigning_user"),
    ]

    operations = []
