# Generated by Django 3.0.8 on 2020-07-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0084_merge_20200611_1311"),
        ("api", "0084_task_reviewers"),
    ]

    operations = []
