# Generated by Django 3.0.8 on 2020-07-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0085_merge_20200721_2045"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="ms_commits",
            new_name="metecho_commits",
        ),
    ]
