# Generated by Django 3.1 on 2020-08-17 15:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0086_rename_ms_commits_metecho_commits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="available_task_org_config_names",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_users",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="repository",
            name="github_users",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="ignored_changes",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="latest_revision_numbers",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="unsaved_changes",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="valid_target_directories",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_dev",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_qa",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="commits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="task",
            name="metecho_commits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="task",
            name="reviewers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
