# Generated by Django 3.1.4 on 2020-12-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0087_django_3_1"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="Epic",
        ),
        migrations.RenameModel(
            old_name="ProjectSlug",
            new_name="EpicSlug",
        ),
    ]
