# Generated by Django 3.1.4 on 2020-12-08 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0088_rename_project_epic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="project",
            new_name="epic",
        ),
        migrations.AlterField(
            model_name="epic",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="epics",
                to="api.repository",
            ),
        ),
    ]
