# Generated by Django 3.1.4 on 2020-12-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_rename_project_fks_epic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Repository",
            new_name="Project",
        ),
        migrations.RenameModel(
            old_name="RepositorySlug",
            new_name="ProjectSlug",
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("name",)},
        ),
        migrations.RenameField(
            model_name="epic",
            old_name="repository",
            new_name="project",
        ),
    ]
