# Generated by Django 3.1.6 on 2021-02-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_rename_repository_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date of the last time the user completed the interactive onboarding",
                null=True,
            ),
        ),
    ]
