# Generated by Django 3.1.5 on 2021-01-13 21:13

import django.db.models.deletion
import sfdo_template_helpers.fields.string
from django.db import migrations, models


def forwards(apps, schema_editor):
    pass


def backwards(apps, schema_editor):
    ScratchOrg = apps.get_model("api", "ScratchOrg")
    ScratchOrg.objects.filter(task__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_rename_repository_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="epic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orgs",
                to="api.epic",
            ),
        ),
        migrations.AddField(
            model_name="scratchorg",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orgs",
                to="api.project",
            ),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="org_type",
            field=sfdo_template_helpers.fields.string.StringField(
                choices=[("Dev", "Dev"), ("QA", "QA"), ("Playground", "Playground")]
            ),
        ),
        migrations.AlterField(
            model_name="scratchorg",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orgs",
                to="api.task",
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
