# Generated by Django 3.1.6 on 2021-02-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0091_playground_orgs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epic",
            name="available_task_org_config_names",
        ),
        migrations.RemoveField(
            model_name="epic",
            name="currently_fetching_org_config_names",
        ),
        migrations.AddField(
            model_name="project",
            name="currently_fetching_org_config_names",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="org_config_names",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
