# Generated by Django 3.1.6 on 2021-02-04 21:44

import sfdo_template_helpers.fields.markdown
import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0092_project_org_config_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="description",
            field=sfdo_template_helpers.fields.markdown.MarkdownField(
                blank=True, property_suffix="_markdown"
            ),
        ),
        migrations.AddField(
            model_name="scratchorg",
            name="org_config_name",
            field=sfdo_template_helpers.fields.string.StringField(default=""),
            preserve_default=False,
        ),
    ]
