# Generated by Django 3.1.6 on 2021-02-12 17:31

import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0093_scratch_org_description_org_config_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="epic",
            name="latest_sha",
            field=sfdo_template_helpers.fields.string.StringField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="latest_sha",
            field=sfdo_template_helpers.fields.string.StringField(blank=True),
        ),
    ]
