# Generated by Django 3.1.6 on 2021-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0094_project_epic_latest_sha"),
    ]

    operations = [
        migrations.AddField(
            model_name="epic",
            name="currently_creating_branch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="currently_creating_branch",
            field=models.BooleanField(default=False),
        ),
    ]
