# Generated by Django 3.1.7 on 2021-02-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0091_user_onboarded_at"),
        ("api", "0095_currently_creating_branch"),
    ]

    operations = []
