# Generated by Django 3.1.7 on 2021-04-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0096_merge_20210224_1518"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="self_guided_tour_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="self_guided_tour_state",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
