# Generated by Django 3.2 on 2021-04-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0097_githubrepository_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_dev_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_qa_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
