# Generated by Django 3.2 on 2021-04-22 14:45

import sfdo_template_helpers.fields.string
from django.db import migrations
from django.db.models import Q


def set_org_owner_gh_id(apps, schema_editor):
    ScratchOrg = apps.get_model("api", "ScratchOrg")
    for instance in ScratchOrg.objects.filter(
        Q(owner_gh_id="") | Q(owner_gh_id__isnull=True)
    ):
        github_account = instance.owner.socialaccount_set.filter(
            provider="github"
        ).first()
        if github_account:
            instance.owner_gh_id = github_account.uid
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0100_remove_task_assignee_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="owner_gh_id",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True, null=True
            ),
        ),
        migrations.RunPython(set_org_owner_gh_id, migrations.RunPython.noop),
    ]
