# Generated by Django 3.2 on 2021-04-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0097_self_guided_tour"),
        ("api", "0101_scratchorg_owner_gh_id"),
    ]

    operations = []
