# Generated by Django 3.2.4 on 2021-06-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0103_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="currently_fetching_github_users",
            field=models.BooleanField(default=False),
        ),
    ]
