# Generated by Django 3.2.9 on 2021-12-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0107_add_github_issues"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="has_truncated_issues",
            field=models.BooleanField(default=False),
        ),
    ]
