# Generated by Django 4.0.4 on 2022-05-26 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_project_has_truncated_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratchorg',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
