# Generated by Django 4.0.4 on 2022-06-02 16:46

import hashid_field.field
import sfdo_template_helpers.fields.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0108_project_has_truncated_issues"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubOrganization",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",  # noqa
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("name", sfdo_template_helpers.fields.string.StringField()),
                (
                    "login",
                    sfdo_template_helpers.fields.string.StringField(
                        help_text="Organization's 'username' on GitHub", unique=True
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, verbose_name="Avatar URL")),
            ],
            options={
                "verbose_name": "GitHub organization",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProjectDependency",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",  # noqa
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("name", sfdo_template_helpers.fields.string.StringField()),
                ("url", models.URLField()),
                ("recommended", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "project dependency",
                "verbose_name_plural": "project dependencies",
                "ordering": ("-recommended", "name"),
            },
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="template_repo_name",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True,
                help_text="Name of the GitHub repository to be used as a template for new Projects",  # noqa
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="template_repo_owner",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True,
                help_text="Owner of the GitHub repository to be used as a template for new Projects",  # noqa
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="currently_fetching_orgs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="organizations",
            field=models.ManyToManyField(
                related_name="users", to="api.githuborganization"
            ),
        ),
    ]
