# Generated by Django 4.0.2 on 2022-02-07 19:36

import sfdo_template_helpers.fields.string
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0109_add_organizations_and_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="template_repo_name",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True,
                help_text="Name of the GitHub repository to be used as a template for new Projects",  # noqa
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="template_repo_owner",
            field=sfdo_template_helpers.fields.string.StringField(
                blank=True,
                help_text="Owner of the GitHub repository to be used as a template for new Projects",  # noqa
            ),
        ),
    ]
