# Generated by Django 4.0.2 on 2022-02-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0110_add_siteprofile_template_repo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currently_fetching_orgs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="organizations",
            field=models.ManyToManyField(
                related_name="users", to="api.GitHubOrganization"
            ),
        ),
    ]
