# Generated by Django 4.0.2 on 2022-02-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0110_add_siteprofile_template_repo"),
    ]

    operations = [
        migrations.AddField(
            model_name="githuborganization",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
