# Generated by Django 4.0.6 on 2022-07-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0110_alter_scratchorg_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="organizations",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="api.githuborganization"
            ),
        ),
    ]
