# Generated by Django 4.0.6 on 2022-07-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0111_add_task_dataset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scratchorg",
            old_name="currently_capturing_changes",
            new_name="currently_retrieving_metadata",
        ),
    ]
