# Generated by Django 4.0.4 on 2022-05-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0112_githuborganization_avatar_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectdependency",
            options={
                "ordering": ("name",),
                "verbose_name": "project dependency",
                "verbose_name_plural": "project dependencies",
            },
        ),
    ]
