# Generated by Django 4.0.5 on 2022-07-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0113_github_models_populate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="github_users_json",
        ),
        migrations.RemoveField(
            model_name="epic",
            name="github_users_json",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_dev_old",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_qa_old",
        ),
        migrations.DeleteModel(
            name="githubrepository",
        ),
    ]
