# Generated by Django 4.0.6 on 2022-08-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_add_task_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratchorg',
            name='currently_retrieving_omnistudio',
            field=models.BooleanField(default=False),
        ),
    ]
