# Generated by Django 4.0.6 on 2022-10-20 22:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_scratchorg_currently_retrieving_omnistudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratchorg',
            name='installed_packages',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
