# Generated by Django 4.0.6 on 2023-05-25 13:54

from django.db import migrations
import sfdo_template_helpers.fields.string


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_project_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='project_namespace',
            field=sfdo_template_helpers.fields.string.StringField(blank=True, help_text='Namespace to be used for new Projects. Leave blank for no namespace.'),
        ),
    ]
